### PR TITLE
Fixed a couple of submodule commits for 2.0.1

### PR DESCRIPTION
**Pull request by aelmahmoudy**
I hadn't tested the build yet. But you mentioned something about the resources

### CODE REVIEW

**Comment by aelmahmoudy** [comment]
Just tested the build & it completed successfully.

**Comment by krt16s** [comment]
I cannot confirm this:


````
:OsmAnd:compileFullLegacyFatReleaseJava/home/krt/src/fdroiddata/build/net.osmand.plus/android/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java:703: error: cannot find symbol
					return uiCtx.getResources().getDrawable(R.drawable.mx_barrier_toll_booth);
					                                                  ^
  symbol:   variable mx_barrier_toll_booth
  location: class drawable
````

**Comment by aelmahmoudy** [comment]
did you run: git submodule update ?

**Comment by krt16s** [comment]
This is done by fdroid automatically, but even when building without fdroid, the same error occurs. I'll try a clean checkout tonight.

**Comment by krt16s** [comment]
Same results. Could you go to your build directory and look for `mx_barrier_toll_booth` (imho it should be a png..)

**Comment by krt16s** [comment]
Upstreams 4201c29cdded293a3a0f7bc7e221d1a0f9957db2 should fix resource issues.

**Comment by aelmahmoudy** [comment]
$ find android/OsmAnd/res/ -name 'mx_barrier_toll_booth.*'0
android/OsmAnd/res/drawable-mdpi/mx_barrier_toll_booth.png
android/OsmAnd/res/drawable-xxhdpi/mx_barrier_toll_booth.png
android/OsmAnd/res/drawable-xhdpi/mx_barrier_toll_booth.png
android/OsmAnd/res/drawable-hdpi/mx_barrier_toll_booth.png

-- 
 ‎أحمد المحمودي (Ahmed El-Mahmoudy)
  Digital design engineer
 GPG KeyID: 0xEDDDA1B7
 GPG Fingerprint: 8206 A196 2084 7E6D 0DF8  B176 BC19 6A94 EDDD A1B7

**Comment by aelmahmoudy** [comment]
After sending you the previous reply, I did a: git clean -dfx, and rebuilt, and indeed I got the error on the missing 'mx_barrier_toll_booth'

I tried updating to v2.0.2 (which includes 4201c29cdded293a3a0f7bc7e221d1a0f9957db2 resources commit) yet still I get the error indeed.

**Comment by aelmahmoudy** [comment]
I fixed it here: https://github.com/osmandapp/Osmand/pull/1171

**Comment by krt16s** [comment]
Just in time, was on my way to use `prebuild=sed -i -e 's/mx_barrier_toll_booth/mx_barrier/g' src/net/osmand/plus/helpers/WaypointHelper.java`

**Pull request merged**
